---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

dotfiles_repo: https://github.com/haraldooo/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dev/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - curlie
  - doxygen
  - fd
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - jq
  - libevent
  - sqlite
  - mas
  - mcrypt
  - nmap
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - xh
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - microsoft-edge
  - handbrake
  - licecap
  - sequel-ace
  - sqlitestudio
  - visual-studio-code
  - powershell
  - affinity-designer
  - affinity-publisher
  - affinity-photo
  - iterm2
  - vagrant
  - spotify
  - bitwarden



# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
 - { id: 497799835, name:  "Xcode" }
 - { id: 409183694, name:  "Keynote" }
 - { id: 1147396723, name: "WhatsApp" }
 - { id: 1295203466, name: "Microsoft Remote Desktop" }
 - { id: 408981434, name:  "iMovie" }
 - { id: 472226235, name:  "LanScan" }
 - { id: 1451685025, name: "WireGuard" }
 - { id: 409201541, name:  "Pages" }
 - { id: 682658836, name:  "GarageBand" }
 - { id: 409203825, name:  "Numbers" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
